site_name: RapiD Vision Documentation
site_url: https://rapid-engineering.github.io/RapiDVision.Docs/
repo_url: https://github.com/RapiD-Engineering/RapiDVision.Docs
repo_name: RapiD-Engineering/RapiDVision.Docs
docs_dir: docs

theme:
  font:
    code: Red Hat Mono
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RapiD-Engineering/RapiDVision.Docs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/rapidengineering/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@rapidengineering2055

copyright: Copyright &copy; 2026 RapiD Engineering, Inc. All rights reserved. RapiD Vision is a trademark of RapiD Engineering, Inc.


plugins:
  - search

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - RapiD Vision:
    - Overview: rapid-vision/index.md
    - Camera Calibration: rapid-vision/camera-calibration.md
    - Connecting a Robot: rapid-vision/connecting-a-robot.md
    - Calibrating a Robot: rapid-vision/calibrating-a-robot.md
    - Encoder Info: rapid-vision/encoder-info.md
    - Sorting Recipes: rapid-vision/sorting-recipes.md
    - Camera Settings: rapid-vision/camera-settings.md
    - Detection Stream Styling: rapid-vision/detection-stream-styling.md
  - RapiD Vision Explorer:
    - Overview: rapid-vision-explorer/index.md
    - Filters: rapid-vision-explorer/filters.md
    - Sorting: rapid-vision-explorer/sorting.md
    - Reporting: rapid-vision-explorer/reporting.md
    - Settings: rapid-vision-explorer/settings.md
    - Analytics: rapid-vision-explorer/analytics.md
    - Alerts: rapid-vision-explorer/alerts.md
  - RapiD Vision API:
    - Overview: rapid-vision-api/index.md
    - Batch: rapid-vision-api/batch.md
    - Invoice: rapid-vision-api/invoice.md
    - InvoiceRule: rapid-vision-api/invoicerule.md
    - Products: rapid-vision-api/products.md
